### ISSUE TITLE
Root Password for 3.0 image

### ISSUE THREAD

**Issue by jwusch** [Irdroid/Irdroid-WiFi-Relay-Board#1]
Hi, I tried contacting support but no response.  I was wondering what the default root password is for the device.  I tried OpenWRT standard root/password, but no joy.

**Comment by Irdroid** [comment]
Sorry for the delay:

root
irdroid2013

On 10 August 2016 19:11:23 EEST, jwusch notifications@github.com wrote:

> Hi, I tried contacting support but no response.  I was wondering what
> the default root password is for the device.  I tried OpenWRT standard
> root/password, but no joy.
> 
> ---
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/Irdroid/Irdroid-WiFi/issues/1

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.
